### ISSUE TITLE
Import/Build CSS Fonts not working

### ISSUE THREAD

**Issue by AngelMunoz** [AngelMunoz/Perla#32]
**Describe the bug**
When you use a path from the root of the server the font is loaded i.e. `url('/src/fonts/myfont.woff')` but that doesn't work with EsBuild, if you fix the path for esbuild then the fonts are not found by the server, Also currently we're not handling any kind of text/binary loader, and esbuild doesn't know what to do with them.

**To Reproduce**
try to build/serve css like this
```css
/* fonts.css */
@font-face {
    font-family: 'Proxima Nova';
    src: url('prox.eot');
    src: url('prox.woff') format('woff'),
         url('prox.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}

/** Proxima Nova Thin **/
@font-face {
    font-family: 'Proxima Thin';
    src: url('proxthin.eot');
    src: url('proxthin.woff') format('woff'),
         url('proxthin.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}

/** Proxima Nova Bold **/
@font-face {
    font-family: 'Proxima Bold';
    src: url('proxbold.eot');
    src: url('proxbold.woff') format('woff'),
         url('proxbold.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}
```

**Expected behavior**
I expect to have a way to load css files like this, either in a static path or by importing them in a javascript file
